ç#  Altered: 2024/12/26 - 12:26
#  Updated: 2025/01/04 - 15:47
#
#  Copyright (c) 2024-2025, Vilmar Catafesta <vcatafesta@gmail.com>
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################
name: "VoidLinux ISO Builder"
description: "Action to build a custom ISO for VoidBR"

inputs:
  teste_input:
    type: boolean
    description: "Enable only test"
    required: false
    default: false
  vol_id:
    description: "Nome do VOLUME da ISO"
    required: true
    default: "VOID_LIVE"
  edition:
    description: "Edition of the ISO"
    required: true
    default: "base"
    options:
      - teste
      - base
      - awesome
      - cinnamon
      - enlightenment
      - fluxbox
      - gnome
      - plasma
      - xfce
      - mate
      - fullx
      - all
  tmate:
    description: "Enable debugging with tmate"
    required: false
  release_tag:
    description: "Release tag for the ISO"
    required: false
  github_token:
    description: "GitHub token for authentication"
    required: true
  iso_basename:
    description: "Nome da ISO"
    required: true

outputs:
  iso_path:
    description: "Path to the generated ISO file"
    value: ${{ steps.build.outputs.iso_path }}
  release_name:
    description: "Name of the release"
    value: ${{ steps.prepare-iso.outputs.release_name }}
  KERNEL_VERSION:
    description: "Kernel version detected"
    value: ${{ steps.build_id.outputs.KERNEL_VERSION }}
  OUTPUT_FILE:
    description: "Filename iso generated for mkiso"
    value: ${{ steps.build_id.outputs.OUTPUT_FILE }}

runs:
  using: "composite"
  steps:
    - name: Export ISO_BASENAME
      shell: bash
      run: |
        echo "ISO_BASENAME=${{ inputs.iso_baeename }}" >> $GITHUB_ENV

    - name: Debug teste_input
      shell: bash
      run: |
        echo "teste_input: '${{ inputs.teste_input }}'"

    - name: Display the current user in CONTAINER
      shell: bash
      run: |
        #Display the current user in CONTAINER
        source /tmp/send_telegram_message.sh
        msg "Display the current user in CONTAINER"
        replicate '='
        msg_raw "${cyan}Current host is     : ${yellow}$(hostname)${reset}"
        msg_raw "${cyan}Current user is     : ${yellow}$(whoami)${reset}"
        msg_raw "${cyan}Current user ID is  : ${yellow}$(id -u)${reset}"
        msg_raw "${cyan}Current user details: ${yellow}$(id)${reset}"
        replicate '='
        msg_info 'duf -all || true'
        duf -all || true
        replicate '='
        msg_info 'ls -la /mnt || true'
        ls -la /mnt || true
        replicate '='

    - name: Configurar o ambiente
      shell: bash
      run: |
        #Configurar o ambiente
        source /tmp/send_telegram_message.sh
        msg "Configurar o ambiente"
        WORK_PATH="/__w/${{env.REPO_NAME}}/${{env.REPO_NAME}}"
        PROFILE_PATH="/__w/${{env.REPO_NAME}}/${{env.REPO_NAME}}/chili-void-mklive"
        BASHRC_PATH="/__w/${{env.REPO_NAME}}/${{env.REPO_NAME}}/chili-void-bashrc"
        msg_tab "WORK_PATH=$WORK_PATH"
        msg_tab "PROFILE_PATH=$PROFILE_PATH"
        msg_tab "BASHRC_PATH=$BASHRC_PATH"
        echo "WORK_PATH=$WORK_PATH"       >> "$GITHUB_ENV"  # Exporta WORK_PATH para outras etapas
        echo "PROFILE_PATH=$PROFILE_PATH" >> "$GITHUB_ENV"  # Exporta WORK_PATH para outras etapas
        echo "BASHRC_PATH=$BASHRC_PATH"   >> "$GITHUB_ENV"  # Exporta WORK_PATH para outras etapas

    - name: Checkout chili-void-mklive
      if: ${{ inputs.teste_input != true }}
      shell: bash
      run: |
        #Checkout chili-void-mklive
        #REPO="${{ inputs.iso_profiles_repo }}"
        REPO="https://github.com/chililinux/chili-void-mklive"
        echo "Repository: $REPO"

        rm -rf "$PROFILE_PATH" || true
        if ! git clone --depth 1 "$REPO" "$PROFILE_PATH"; then
          echo "Falha ao clonar o repositorio $REPO em $PROFILE_PATH"
          exit 1
        fi
        # ativando 'git config --global --add safe.directory'
        git config --global --add safe.directory "$PROFILE_PATH" || true

        # clean '/__t/' directory
        rm -rf /__t/* || true

    #    - name: Checkout chili-void-bashrc
    #      if: ${{ inputs.teste_input != true }}
    #      shell: bash
    #      run: |
    #        #Checkout chili-void-bashrc
    #        source /tmp/send_telegram_message.sh
    #        msg "Checkout chili-void-bashrc"
    #        replicate '='
    #        #REPO="${{ inputs.iso_profiles_repo }}"
    #        REPO="https://github.com/chililinux/chili-void-bashrc"
    #        echo "Repository: $REPO"
    #
    #        rm -rf "$BASHRC_PATH" || true
    #        if ! git clone --depth 1 "$REPO" "$BASHRC_PATH"; then
    #          echo "Falha ao clonar o repositorio $REPO em $BASHRC_PATH"
    #          exit 1
    #        fi
    #        # ativando 'git config --global --add safe.directory'
    #        git config --global --add safe.directory "$BASHRC_PATH" || true
    #        replicate '='

    - name: Ajustar wheel
      shell: bash
      run: |
        echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" >>"/etc/sudoers.d/wheel"

    - name: Ajustar ambiente
      shell: bash
      run: |
        source /tmp/send_telegram_message.sh
        msg "- name: Ajustar ambiente"
        replicate '='
        echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" >>"/etc/sudoers.d/wheel"
        ln -sfv "$WORK_PATH" /work_path || true
        #cp -Rpa "$BASHRC_PATH"/etc/. /etc/ || true

        configure_users_path() {
          local apaths=('/root' '/github/home' '/home/builduser')
          local auser=('builduser' 'vcatafesta')
          local cpath

          for cpath in "${apaths[@]}"; do
            replicate '#'
            msg "Ajustando ambiente em $cpath"
            pushd "$cpath"         || true
            cp -Rpa /etc/skel/. .  || true
            popd || true
          done

          for cuser in "${auser[@]}"; do
            replicate '#'
            msg "Ajustando permissões user '$cuser'"
            pushd /home/$cuser            || true
            sudo chown $cuser:$cuser . -R || true
            ls -la /home/$cuser           || true
            popd || true
          done
          replicate '='
        }
        configure_users_path

    - name: Build ISO ${{ inputs.edition }}
      id: build_id
      if: ${{ inputs.teste_input != true }}
      shell: bash
      env:
        DEBUG: "${{ inputs.tmate }}"
        TESTE: "${{ inputs.teste_input }}"
        VOL_ID: "${{ inputs.vol_id }}"
        EDITION: "${{ inputs.edition }}"
        RELEASE_TAG: "${{ inputs.release_tag }}"
      run: |
        #BUILD ISO Image
        source /tmp/send_telegram_message.sh
        msg "BUILD ISO Image"
        # Check if directory exists before proceeding
        if [[ ! -d "$PROFILE_PATH" ]]; then
          msg_warning "ERRO(L427): Diretório $PROFILE_PATH não encontrado!"
          exit 1
        fi

        build_iso() {
          local BUILD_COMMAND

          case "$EDITION" in
            base)         BUILD_COMMAND='bash ./mkiso --automatic'    ;;
            awesome)      BUILD_COMMAND='bash ./mkiso --automatic -W' ;;
            cinnamon)     BUILD_COMMAND='bash ./mkiso --automatic -N' ;;
            enlightnment) BUILD_COMMAND='bash ./mkiso --automatic -E' ;;
            fluxbox)      BUILD_COMMAND='bash ./mkiso --automatic -F' ;;
            gnome)        BUILD_COMMAND='bash ./mkiso --automatic -G' ;;
            plasma)       BUILD_COMMAND='bash ./mkiso --automatic -P' ;;
            xfce)         BUILD_COMMAND='bash ./mkiso --automatic -Y' ;;
            mate)         BUILD_COMMAND='bash ./mkiso --automatic -M' ;;
            all)          BUILD_COMMAND='bash ./mkiso --automatic -A' ;;
            *)            BUILD_COMMAND='bash ./mkiso --automatic'    ;;
          esac

          msg_raw "${red}########################## RESUMO ######################################################${reset}"
          msg_raw "DEBUG (tmate)            : ${yellow}$DEBUG"
          msg_raw "TESTE                    : ${yellow}${{ inputs.teste_input }}"
          msg_raw "VOL_ID                   : ${yellow}$VOL_ID"
          msg_raw "EDITION                  : ${yellow}$EDITION"
          msg_raw "RELEASE_TAG              : ${yellow}$RELEASE_TAG"
          msg_raw "${red}########################################################################################${reset}"
          msg_raw "BUILD COMMAND            : ${yellow}$BUILD_COMMAND"
          msg_raw "WORK_PATH                : ${yellow}$WORK_PATH"
          msg_raw "PROFILE_PATH             : ${yellow}$PROFILE_PATH"
          msg_raw "ISO profiles path        : ${yellow}$PROFILE_PATH/$EDITION"
          msg_raw "${red}########################################################################################${reset}"
          pushd "$PROFILE_PATH"

          #teste
          #echo "Arquivo 1 de teste" > arquivo1.txt
          #echo "Arquivo 2 de teste" > arquivo2.txt
          #tar -cvJf void-live-base-custom-x86_64-6.6.51_1-20240920-1810.tar.xz arquivo1.txt arquivo2.txt
          #efetivo
          #[[ ${{ inputs.tmate }} == true ]] && ./mkiso || ./mkiso > /dev/null
          if [[ "$EDITION" == 'teste' ]]; then
            replicate
            DATA_HORA="$(date +'%Y%m%d-%H%M')"
            TEST_FILENAME="voidbr-live-teste-x86_64-x86_64-6.12.74_1_${DATA_HORA}.iso"
            msg_raw "Criando iso de teste : $TEST_FILENAME"
            dd if=/dev/zero of="$TEST_FILENAME" bs=2300M count=1 status=none
            ls -la --color=auto || true
            replicate
          else
            eval "$BUILD_COMMAND"
          fi
          popd
          replicate
        }
        export -f build_iso

        export_kernel_vars() {
          source /tmp/send_telegram_message.sh
          replicate

          FILE_KERNEL_EDITION="$PROFILE_PATH/kernel-${EDITION}.txt"
          msg "Capturando kernel version from : $PROFILE_PATH/$FILE_KERNEL_EDITION"
          [[ -e "$FILE_KERNEL_EDITION" ]] && source "$FILE_KERNEL_EDITION"
          msg_raw "FILE_KERNEL_EDITION : kernel-${EDITION}.txt"
          msg_raw "KERNEL_VERSION      : $KERNELVERSION"
          msg_raw "OUTPUT_FILE         : $OUTPUT_FILE"
          echo "KERNEL_VERSION=$KERNELVERSION" >> "$GITHUB_ENV"
          echo "OUTPUT_FILE=$OUTPUT_FILE"      >> "$GITHUB_ENV"
          replicate
        }
        export -f export_kernel_vars

        # No action.yml
        cleanup_and_move_files() {
          msg "cleanup_and_move_files"
          msg_raw "PROFILE_PATH           : $PROFILE_PATH"

          OUTPUT_ISO_PATH_NAME=$(find "$PROFILE_PATH" -type f -name "*.iso" -exec stat -c '%Y %n' {} + | sort -nr | awk 'NR==1 {print $2}')
          ISO_BASENAME=$(basename "$OUTPUT_ISO_PATH_NAME")

          [[ -z "$OUTPUT_ISO_PATH_NAME" ]] && { echo "ERRO: ISO não encontrada"; exit 1; exit 1; }

          msg_raw "Arquivo ISO encontrado : $OUTPUT_ISO_PATH_NAME"
          msg_raw "OUTPUT_ISO_PATH_NAME   : $OUTPUT_ISO_PATH_NAME"
          msg_raw "ISO_BASENAME           : $ISO_BASENAME"

          echo "OUTPUT_ISO_PATH_NAME=$OUTPUT_ISO_PATH_NAME" >> "$GITHUB_ENV"
          echo "ISO_BASENAME=$ISO_BASENAME"                 >> "$GITHUB_ENV"

          msg_run "mv -fv $OUTPUT_ISO_PATH_NAME $WORK_PATH/" || echo "ERRO: Falha ao mover arquivo ISO $OUTPUT_ISO_PATH_NAME"
          # Set environment variables
          msg_raw "ISO_FULLNAME : $WORK_PATH/$ISO_BASENAME"
          echo "ISO_FULLNAME=$WORK_PATH/$ISO_BASENAME" >> "$GITHUB_ENV"
        }
        export -f cleanup_and_move_files

        build_iso
        cleanup_and_move_files
        export_kernel_vars

    - name: Extrair data do nome do arquivo .iso e definir tag_name
      if: ${{ inputs.teste_input != true }}
      id: set-tag-name
      shell: bash
      run: |
        source /tmp/send_telegram_message.sh
        msg "Extrair data do nome do arquivo .iso e definir tag_name"
        FILENAME="$ISO_BASENAME"
        TAG_NAME="$(echo "$FILENAME" | grep -oP '\d{8}')-$(date +%H%M)"
        msg "ISO_FILENAME=$FILENAME"
        msg "ISO_TAG_NAME=$TAG_NAME"
        echo "ISO_FILENAME=$FILENAME" >> $GITHUB_ENV
        echo "ISO_TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

    - name: Set ISO path
      if: ${{ inputs.teste_input != true }}
      shell: bash
      run: |
        source /tmp/send_telegram_message.sh
        replicate
        msg "- name: Set ISO path"
        msg_raw "iso_path : $WORK_PATH/$ISO_BASENAME"
        msg_raw "ISO_PATH : $WORK_PATH/$ISO_BASENAME"

        echo "iso_path=$WORK_PATH/$ISO_BASENAME" >> $GITHUB_OUTPUT
        echo "ISOPATH=$WORK_PATH/$ISO_BASENAME" >> $GITHUB_ENV

        replicate
